Repository Dubutoto/SANTA1.0, pull requests merged in 2025-01, with the labels that each got.

#8 [Feat] 게시판 기능 추가(미완성)
  src/main/java/com/example/santa/board/mapper/BoardMapper.java
  src/main/java/com/example/santa/board/service/BoardService.java
  src/main/java/com/example/santa/board/vo/BoardVO.java
  src/main/java/com/example/santa/reply/mapper/ReplyMapper.java
  src/main/java/com/example/santa/reply/service/ReplyService.java
  src/main/java/com/example/santa/reply/vo/ReplyVO.java
  src/main/resources/mapper/BoardMapper.xml
  src/main/resources/mapper/ReplyMapper.xml
Labels: ✨ Feature

#13 [PR] 메인 최신화
  .gitignore
  Santa_Query_V2.sql
  logs/app.log
  src/main/java/com/example/santa/board/mapper/Board.java
  src/main/java/com/example/santa/board/vo/BoardVO.java
  src/main/java/com/example/santa/reply/mapper/BoardMapper.java
  src/main/java/com/example/santa/reply/vo/BoardVO.java
  src/main/resources/mapper/BoardMapper.xml
Labels: ✅PR

#18 [Feat] 출고 관리, 배송 관리, map api(경유지 최적화) 기능 추가
  .gitignore
  Santa_Query_V2.sql
  src/main/java/com/example/santa/board/mapper/Board.java
  src/main/java/com/example/santa/board/vo/BoardVO.java
  src/main/java/com/example/santa/config/SecurityConfig.java
  src/main/java/com/example/santa/outgoing/controller/OutgoingController.java
  src/main/java/com/example/santa/outgoing/mapper/OutgoingMapper.java
  src/main/java/com/example/santa/outgoing/service/OutgoingService.java
  src/main/java/com/example/santa/outgoing/vo/OutgoingDTO.java
  src/main/java/com/example/santa/outgoing/vo/OutgoingDetailsDTO.java
  src/main/java/com/example/santa/reply/mapper/BoardMapper.java
  src/main/java/com/example/santa/reply/vo/BoardVO.java
  src/main/java/com/example/santa/transit/controller/TransitController.java
  src/main/java/com/example/santa/transit/mapper/TransitMapper.java
  src/main/java/com/example/santa/transit/service/TransitService.java
  src/main/java/com/example/santa/transit/vo/TransitDTO.java
  src/main/java/com/example/santa/transit/vo/TransitVO.java
  src/main/resources/application.properties
  src/main/resources/mapper/BoardMapper.xml
  src/main/resources/mapper/OutgoingMapper.xml
  src/main/resources/mapper/TransitMapper.xml
  src/main/resources/static/assets/img/map/pin_r_s.png
  src/main/resources/static/map.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/outgoing/ougoingRead.html
  src/main/resources/templates/outgoing/outgoingApprove.html
  src/main/resources/templates/outgoing/outgoingRead.html
  src/main/resources/templates/transit/mapOptimization.html
  src/main/resources/templates/transit/transitApprove.html
  src/main/resources/templates/transit/transitRead.html
Labels: 🐞 BugFix, 🌏 Deploy, ✅PR, 🎨 Html&css, ✨ Feature

#24 가자
  src/main/java/com/example/santa/inventory/controller/InventoryController.java
  src/main/java/com/example/santa/inventory/mapper/InventoryMapper.java
  src/main/java/com/example/santa/inventory/service/InventoryService.java
  src/main/java/com/example/santa/inventory/vo/InventoryDTO.java
  src/main/java/com/example/santa/order/controller/OrderController.java
  src/main/resources/mapper/inventoryMapper.xml
  src/main/resources/templates/inventory/categoryRead.html
  src/main/resources/templates/inventory/warehouseRead.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/order/approval.html
  src/main/resources/templates/order/read.html
  src/main/resources/templates/order/test2.html
Labels: 📃 Docs, ⚙ Setting, ✅PR, 🎨 Html&css, ✨ Feature

#34 Develop
  src/main/java/com/example/santa/register/service/TransitScheduler.java
  src/main/java/com/example/santa/transit/mapper/TransitMapper.java
  src/main/java/com/example/santa/transit/service/TransitService.java
  src/main/java/com/example/santa/transit/service/TransitServiceInterface.java
  src/main/resources/mapper/TransitMapper.xml
  src/main/resources/templates/transit/map.html
Labels: ✅PR, ✨ Feature, 🔨 Refactor
